server:
  port: 8080 # ??????

spring:
  datasource:
    # ??????????? diet_system ????
    url: jdbc:mysql://localhost:3306/diet_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root # ?? MySQL ???
    password: 123456 # ?? MySQL ??
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus ??
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ?????? SQL ???????
    map-underscore-to-camel-case: true # ??????????????????
  global-config:
    db-config:
      id-type: assign_id # ?????????? ID